name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Tests/AiRiseBackend.Tests/AiRise.Tests.csproj

      - name: Build
        run: dotnet build Tests/AiRiseBackend.Tests/AiRise.Tests.csproj -c Release --no-restore

      # NEW STEP: Install MongoDB dependencies for Ubuntu (fixes libssl1.1 issue)
      - name: Install MongoDB dependencies
        run: |
          sudo apt update
          echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
          sudo apt update
          sudo apt install -y libssl1.1

      - name: Test
        run: dotnet test  Tests/AiRiseBackend.Tests/AiRise.Tests.csproj -c Release --no-build --verbosity normal
